dependencies {
	jarJar(api("net.swedz:tesseract-api:${tesseract_version}")) {
		version {
			strictly tesseract_version_range
			prefer tesseract_version
		}
	}

	// TODO wait for EMI
	/*if (project.runtime_include_emi.toBoolean()) {
		localImplementation "dev.emi:emi-neoforge:${emi_version}"
	} else {
		compileOnly "dev.emi:emi-neoforge:${emi_version}"
	}*/

	// TODO wait for MI
	/*if (project.runtime_include_mi.toBoolean()) {
		localImplementation "aztech:Modern-Industrialization:${modern_industrialization_version}"
	} else {
		compileOnly "aztech:Modern-Industrialization:${modern_industrialization_version}"
	}*/
}