# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Settings
runtime_include_emi=false
runtime_include_mi=false

# Gradle Configuration
artifact_name=tesseract-api-neoforge

# Publishing
deploy_name=Tesseract API (NeoForge)
deploy_discord_icon=https://cdn.discordapp.com/emojis/1264330203786903584.webp
compatible_minecraft_versions=26.1.2
curseforge_project=1067672
curseforge_project_slug=tesseract-api-neoforge
curseforge_project_relations=modern-industrialization:optional
modrinth_project=pHNT1iyc
modrinth_project_slug=tesseract-api
modrinth_project_relations=modern-industrialization:optional

# NeoForge Environment
minecraft_version=26.1.2
neoforge_version=26.1.2.87
loader_version_range=[2,)

# Mod Properties
mod_id=tesseract_api
mod_name=Tesseract API
mod_group_id=net.swedz
mod_authors=Swedz
mod_description=Another library mod for mod developers
mod_github=https://github.com/Swedz/tesseract-neoforge

# Dependencies
tesseract_version=1.0.1
tesseract_version_range=[1.0.1-,1.1-)
emi_version=1.1.10+1.21
modern_industrialization_version=2.5.0-dev
modern_industrialization_version_range=[2.5.0-dev-, 2.6-)